services:
  db:
    image: postgres:16-alpine
    container_name: clients_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clients_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: clients_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://user:password@db:5432/clients_db
    restart: always
    command: sh -c "python seed_dev.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
